name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-wasm:
    strategy:
      matrix:
        features: ["default", "debug", "console_log", "debug,console_log"]
    name: Check - WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --target wasm32-unknown-unknown --features ${{ matrix.features }}

  check-linux:
    strategy:
      matrix:
        features:
          [
            "default",
            "debug",
            "profile",
            "dynamic",
            "debug,profile",
            "debug,dynamic",
            "profile,dynamic",
            "debug,profile,dynamic",
          ]
    name: Check - x86-64 Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - run: cargo check --target x86_64-unknown-linux-gnu --features ${{ matrix.features }}

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly fmt --all -- --check

  clippy-wasm:
    strategy:
      matrix:
        features: ["default", "debug", "console_log", "debug,console_log"]
    name: Clippy - WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly clippy --target wasm32-unknown-unknown --features ${{ matrix.features }} -- --D warnings

  clippy-linux:
    strategy:
      matrix:
        features:
          [
            "default",
            "debug",
            "profile",
            "dynamic",
            "debug,profile",
            "debug,dynamic",
            "profile,dynamic",
            "debug,profile,dynamic",
          ]
    name: Clippy - x86-64 Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy
          targets: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - run: cargo +nightly clippy --target x86_64-unknown-linux-gnu --features ${{ matrix.features }} -- --D warnings
